# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_table1_field1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Table3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Table4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='table1',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='table3',
            name='table1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table3', to='main.Table1'),
        ),
        migrations.AddField(
            model_name='table2',
            name='table1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables2', to='main.Table1'),
        ),
        migrations.AddField(
            model_name='table1',
            name='tables4',
            field=models.ManyToManyField(to='main.Table4'),
        ),
    ]
